server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: root

  application:
    name: Question-Service

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761


