spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Gajusawale/application-config

# Eureka
eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://serviceregistry:8761

server:
  port: 8084




