#server:
#  port: 8083
#
#spring:
#  application:
#    name: API-GATEWAY
#
##  cloud:
##    gateway:
##      routes[0]:
##        id: QUIZ-SERVICE
##        uri: lb://QUIZ-SERVICE
##        predicates[0]:
##          path: /quiz/**
#
#  cloud:
#    gateway:
#      routes:
#        - id: QUIZ-SERVICE
#          uri: lb://QUIZ-SERVICE
#          predicates:
#            - Path= "/quiz/**"

# Eureka
#eureka:
#  instance:
#    client:
#      serverUrl:
#        defaultZone: http://serviceregistry:8761

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always